apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: Qm9iYnlDbG91ZA==
  CLOUDINARY_KEY: MjY3MzY3MTgzMzk1OTIx
  CLOUDINARY_SECRET: c1FkdWx6bUtIbGlqTGJkMWNRWVRHVzhLbWx3
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZbTlpWW5sd2RXeHNZU0lzSW1FaU9pSmpiVzFyTW1Vd2JHOHdhVGR6TW5CelltaG9hWGN3ZVRBeUluMC5VZTdsTzVWRHg2TjZWN1lMbUFPZUJB
  DB_URL: aHR0cHM6Ly9jbG91ZC5tb25nb2RiLmNvbS92Mi82OWFmOTZmYmQ3MmM2MzVmYmUwMWExYTIjL2NsdXN0ZXJzL2RldGFpbC9NeUNsdXN0ZXI=
