apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: Qm9iYnlDbG91ZA==
  CLOUDINARY_KEY: MjY3MzY3MTgzMzk1OTIx
  CLOUDINARY_SECRET: c1FkdWx6bUtIbGlqTGJkMWNRWVRHVzhLbWx3
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZbTlpWW5sd2RXeHNZU0lzSW1FaU9pSmpiVzFyTW1Vd2JHOHdhVGR6TW5CelltaG9hWGN3ZVRBeUluMC5VZTdsTzVWRHg2TjZWN1lMbUFPZUJB
  DB_URL:bW9uZ29kYitzcnY6Ly9ib2JieTo8YWRtaW4xMjM+QG15Y2x1c3Rlci56d3V4aGw2Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPU15Q2x1c3Rlcg== 
